# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.7
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: witness.code04@gmail.com
author_name: sakshi-419
contract_name: cert_verifier
preset_name: starter
project_name: cert-verifier-contracts

