# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: witness.code04@gmail.com
author_name: sakshi-419
preset_name: starter
project_name: cert-verifier-frontend

